### ISSUE TITLE
Still in 1.1.1

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.cassidyjames.plausible#1]
https://github.com/flathub/com.cassidyjames.plausible/commit/7dc389d177c9335fe2a40c280efd6f37c880ca35 didn't seem to work. We're still in 1.1.1.

![image](https://user-images.githubusercontent.com/50847364/109520622-7015ae80-7a7a-11eb-9b3d-b3d51d61398c.png)

**Comment by cassidyjames** [comment]
I think it was an issue with whitespace; I've pushed a commit to correct it.

**Comment by TheEvilSkeleton** [comment]
@cassidyjames can you rebuild the flatpak?

**Comment by cassidyjames** [comment]
@TheEvilSkeleton I thought it did that automatically; I don't know how to trigger it on my end.

**Comment by TheEvilSkeleton** [comment]
@cassidyjames okay, I think I've figured it out, but I do not have the permissions. Here's what to do:

1. Go to https://flathub.org/builds/#/
2. Press on "Start build" (at the top right)
3. Write the following in the `<code>` formatting:
     - reason: `Publish`
     - branch: `master`
     - repo uri: `https://github.com/flathub/com.cassidyjames.plausible.git`
     - App ID: `com.cassidyjames.plausible`
     - Arches (comma separated): `x86_64, aarc64`

If that doesn't work, then you could rebase to trigger a build.

**Comment by cassidyjames** [comment]
@TheEvilSkeleton ah, no, the issue is the manifest is still pointing to the 1.2.0 release which had the screenshot typo in metainfo. I'm cutting a new 1.2.1 release and will point the manifest to that, which will trigger a new build.

**Comment by TheEvilSkeleton** [comment]
Sure.
